spring:
  #mysql数据库
  datasource:
    url:  jdbc:mysql://10.23.24.18:3306/lionconfig?characterEncoding=UTF-8
    username: root
    password: meiya@20pico
    driverClassName:  com.mysql.cj.jdbc.Driver
  data:
    #MongoDB
    mongodb:
      port: 你的mongoDB的端口 #mongoDB的端口号
      host: 你的mongoDB的IP #mongoDB的连接地址
      database: 你的mongoDB的数据库名称 # mongodb的连接的数据库
      username: 你的mongoDB的账号
      password: 你的mongoDB的密码
      authentication-database: admin #这个不需要改动
#xml文件的路径配置的模糊匹配
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml